export const TODOS_FILTER_ALL = `TODOS_FILTER_ALL`;
export const TODOS_FILTER_COMPLETED = `TODOS_FILTER_COMPLETED`;
export const TODOS_FILTER_PROGRESS = `TODOS_FILTER_PROGRESS`;
export const TODOS_COLOR = `#000`;
export const COMPLETED_TODOS_COLOR = `#008000`;

